//// <auto-generated />
//using System;
//using Habitraca.Persistence.DbContextFolder;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

//#nullable disable

//namespace Habitraca.Persistence.Migrations
//{
//    [DbContext(typeof(HabitDbContext))]
//    [Migration("20250225210027_Rewards")]
//    partial class Rewards
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "6.0.0")
//                .HasAnnotation("Relational:MaxIdentifierLength", 63);

//            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

//            modelBuilder.Entity("Habitraca.Domain.Entities.Graph", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uuid");

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("CreatedBy")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<DateTime>("Date")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<int>("TaskCount")
//                        .HasColumnType("integer");

//                    b.Property<DateTime>("UpdatedAt")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("UpdatedBy")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.HasKey("Id");

//                    b.ToTable("Graphs");
//                });

//            modelBuilder.Entity("Habitraca.Domain.Entities.HabitTask", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uuid");

//                    b.Property<string>("Category")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("CreatedBy")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<string>("Frequency")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("boolean");

//                    b.Property<int>("Points")
//                        .HasColumnType("integer");

//                    b.Property<string>("Title")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<DateTime>("UpdatedAt")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("UpdatedBy")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("Tasks");
//                });

//            modelBuilder.Entity("Habitraca.Domain.Entities.Reward", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uuid");

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("CreatedBy")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<string>("Description")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<string>("Point")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<DateTime>("UpdatedAt")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("UpdatedBy")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.HasKey("Id");

//                    b.ToTable("Rewards");
//                });

//            modelBuilder.Entity("Habitraca.Domain.Entities.TaskCompletion", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uuid");

//                    b.Property<DateTime>("CompletedAt")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("CreatedBy")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<Guid>("TaskId")
//                        .HasColumnType("uuid");

//                    b.Property<DateTime>("UpdatedAt")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("UpdatedBy")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.HasKey("Id");

//                    b.HasIndex("TaskId");

//                    b.HasIndex("UserId");

//                    b.ToTable("TaskCompletions");
//                });

//            modelBuilder.Entity("Habitraca.Domain.Entities.TaskPool", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uuid");

//                    b.Property<string>("Category")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("CreatedBy")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<bool>("IsActive")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("boolean")
//                        .HasDefaultValue(true);

//                    b.Property<int>("Points")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("integer")
//                        .HasDefaultValue(0);

//                    b.Property<string>("Title")
//                        .IsRequired()
//                        .HasMaxLength(255)
//                        .HasColumnType("character varying(255)");

//                    b.Property<DateTime>("UpdatedAt")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("UpdatedBy")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.HasKey("Id");

//                    b.ToTable("TaskPools");
//                });

//            modelBuilder.Entity("Habitraca.Domain.Entities.User", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("text");

//                    b.Property<int>("AccessFailedCount")
//                        .HasColumnType("integer");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("text");

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<DateTime>("DateModified")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("Email")
//                        .HasMaxLength(256)
//                        .HasColumnType("character varying(256)");

//                    b.Property<bool>("EmailConfirmed")
//                        .HasColumnType("boolean");

//                    b.Property<string>("FirstName")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<string>("ImageUrl")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("boolean");

//                    b.Property<string>("LastName")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<bool>("LockoutEnabled")
//                        .HasColumnType("boolean");

//                    b.Property<DateTimeOffset?>("LockoutEnd")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("NormalizedEmail")
//                        .HasMaxLength(256)
//                        .HasColumnType("character varying(256)");

//                    b.Property<string>("NormalizedUserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("character varying(256)");

//                    b.Property<string>("Password")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<string>("PasswordHash")
//                        .HasColumnType("text");

//                    b.Property<string>("PasswordResetToken")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<string>("PhoneNumber")
//                        .HasColumnType("text");

//                    b.Property<bool>("PhoneNumberConfirmed")
//                        .HasColumnType("boolean");

//                    b.Property<DateTime>("ResetTokenExpires")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("SecurityStamp")
//                        .HasColumnType("text");

//                    b.Property<bool>("TwoFactorEnabled")
//                        .HasColumnType("boolean");

//                    b.Property<string>("UserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("character varying(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedEmail")
//                        .HasDatabaseName("EmailIndex");

//                    b.HasIndex("NormalizedUserName")
//                        .IsUnique()
//                        .HasDatabaseName("UserNameIndex");

//                    b.ToTable("AspNetUsers", (string)null);

//                    b.HasData(
//                        new
//                        {
//                            Id = "ecb3225c-b8a3-41c4-b426-fd03daff97e3",
//                            AccessFailedCount = 0,
//                            ConcurrencyStamp = "0569b432-fecd-4402-ac57-4d1d036e270c",
//                            CreatedAt = new DateTime(2025, 2, 25, 21, 0, 26, 832, DateTimeKind.Utc).AddTicks(7769),
//                            DateModified = new DateTime(2025, 2, 25, 21, 0, 26, 832, DateTimeKind.Utc).AddTicks(7776),
//                            Email = "Chuksinnocent1@gmail.com",
//                            EmailConfirmed = false,
//                            FirstName = "Innocent",
//                            ImageUrl = "",
//                            IsActive = true,
//                            LastName = "Chukwudi",
//                            LockoutEnabled = false,
//                            Password = "Password",
//                            PasswordResetToken = "",
//                            PhoneNumber = "07013238817",
//                            PhoneNumberConfirmed = false,
//                            ResetTokenExpires = new DateTime(2025, 2, 25, 21, 0, 26, 832, DateTimeKind.Utc).AddTicks(7775),
//                            SecurityStamp = "6efbc755-8a93-4444-80c0-cb891143aba6",
//                            TwoFactorEnabled = false
//                        });
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("text");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("text");

//                    b.Property<string>("Name")
//                        .HasMaxLength(256)
//                        .HasColumnType("character varying(256)");

//                    b.Property<string>("NormalizedName")
//                        .HasMaxLength(256)
//                        .HasColumnType("character varying(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedName")
//                        .IsUnique()
//                        .HasDatabaseName("RoleNameIndex");

//                    b.ToTable("AspNetRoles", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("integer");

//                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("text");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("text");

//                    b.Property<string>("RoleId")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.HasKey("Id");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetRoleClaims", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("integer");

//                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("text");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("text");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserClaims", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("text");

//                    b.Property<string>("ProviderKey")
//                        .HasColumnType("text");

//                    b.Property<string>("ProviderDisplayName")
//                        .HasColumnType("text");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.HasKey("LoginProvider", "ProviderKey");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserLogins", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("text");

//                    b.Property<string>("RoleId")
//                        .HasColumnType("text");

//                    b.HasKey("UserId", "RoleId");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetUserRoles", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("text");

//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("text");

//                    b.Property<string>("Name")
//                        .HasColumnType("text");

//                    b.Property<string>("Value")
//                        .HasColumnType("text");

//                    b.HasKey("UserId", "LoginProvider", "Name");

//                    b.ToTable("AspNetUserTokens", (string)null);
//                });

//            modelBuilder.Entity("Habitraca.Domain.Entities.HabitTask", b =>
//                {
//                    b.HasOne("Habitraca.Domain.Entities.User", "User")
//                        .WithMany("Tasks")
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("User");
//                });

//            modelBuilder.Entity("Habitraca.Domain.Entities.TaskCompletion", b =>
//                {
//                    b.HasOne("Habitraca.Domain.Entities.HabitTask", "Task")
//                        .WithMany()
//                        .HasForeignKey("TaskId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Habitraca.Domain.Entities.User", "User")
//                        .WithMany("CompletedTasks")
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Task");

//                    b.Navigation("User");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.HasOne("Habitraca.Domain.Entities.User", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.HasOne("Habitraca.Domain.Entities.User", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Habitraca.Domain.Entities.User", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.HasOne("Habitraca.Domain.Entities.User", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Habitraca.Domain.Entities.User", b =>
//                {
//                    b.Navigation("CompletedTasks");

//                    b.Navigation("Tasks");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
